version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - run: 
          name: Verify SPEC_BRANCH
          command: | 
            if [ "$SPEC_BRANCH" = "" ]; then
                circleci-agent step halt
                echo 'SPEC BRANCH NOT SUPPLIED ... HALT BUILD'
            fi
      - checkout
      - run:
          name: Pull Docker Images Local
          command: |
            docker pull mikefarah/yq:latest
      - run: 
          name: Set MASTER_SPEC_OA3_SEMVER
          command: | 
            echo 'export MASTER_SPEC_OA3_SEMVER=$(make WORKING_SPEC=https://raw.githubusercontent.com/${SPEC_PROJECT_USERNAME}/${SPEC_PROJECT_REPONAME}/master/spec/openapi.yaml version)' >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: Set SPEC_OA3_SEMVER
          command: | 
            echo 'export SPEC_OA3_SEMVER=$(make WORKING_SPEC=https://raw.githubusercontent.com/${SPEC_PROJECT_USERNAME}/${SPEC_PROJECT_REPONAME}/${SPEC_BRANCH}/spec/openapi.yaml version)' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Echo Vars
          command: |
            echo SPEC_BRANCH ${SPEC_BRANCH} # param passed in via trigger ie. 'v1.3'
            echo SPEC_PROJECT_USERNAME ${SPEC_PROJECT_USERNAME} # build settings env var
            echo SPEC_PROJECT_REPONAME ${SPEC_PROJECT_REPONAME} # build settings env var
            echo MASTER_SPEC_OA3_SEMVER ${MASTER_SPEC_OA3_SEMVER} # ie. '1.2.2' pulled from spec yaml
            echo SPEC_OA3_SEMVER ${SPEC_OA3_SEMVER} # ie. '1.3.14' pulled from spec yaml
      - run: 
          name: Build the OA3 Client
          command: | 
            make VERSION=${SPEC_OA3_SEMVER} oa3config
            make clean
            make WORKING_SPEC=https://raw.githubusercontent.com/${SPEC_PROJECT_USERNAME}/${SPEC_PROJECT_REPONAME}/${SPEC_BRANCH}/spec/openapi.yaml generate
            sudo chown -R $USER:$USER . # docker volume mounted as root
            make trim
            make info
            make build_client
      - run: 
          name: Run Tests for OA3 Client
          command: | 
            make tests
      - deploy:
          name: Release Version ... Conditionally
          command: |
            git config user.email "$GIT_AUTHOR_EMAIL"
            git config user.name "$GIT_AUTHOR_NAME"

            if [[ SPEC_BRANCH != 'master' ]]; then
              echo 'NOT MASTER SO BUILDING DEV VERSION'
              make VERSION=${SPEC_OA3_SEMVER}.beta${BETA_BUILD} build
              make VERSION=${SPEC_OA3_SEMVER}.beta${BETA_BUILD} commit
              echo ":rubygems_api_key: ${RUBYGEM_TOKEN}" > ~/.gem/credentials
              chmod 0600 /home/circleci/.gem/credentials
              make VERSION=${SPEC_OA3_SEMVER}.beta${BETA_BUILD} publish
            fi

            if [[ SPEC_BRANCH = 'master' ]]; then
              if [[ PUBLISH_RELEASE = 'true' ]]; then
                echo 'MASTER & RELEASE SO BUILDING PROD VERSION'
                make VERSION=${SPEC_OA3_SEMVER} build
                make VERSION=${SPEC_OA3_SEMVER} commit
                echo ":rubygems_api_key: ${RUBYGEM_TOKEN}" > ~/.gem/credentials
                chmod 0600 /home/circleci/.gem/credentials
                make VERSION=${SPEC_OA3_SEMVER} publish
              fi
            fi

workflows:
  version: 2
  build_test_release:
    jobs:
      - build